version: '3.3'

services:

  rversions:
    build:
      context: .
    ports:
      - "3000:80"
    command: nodemon bin/www.js
    volumes:
      - .:/src
    environment:
      REDIS_URL: "redis://:secret@redis:6379"
      GITHUB_TOKEN: ${GITHUB_TOKEN}

  redis:
    image: "redis:7.2.4-alpine"
    volumes:
      - ./redis.conf:/src/redis.conf
    command: [ "redis-server", "/src/redis.conf" ]
