version: '3.3'

volumes:
  rversions-data:

services:

  rversions:
    platform: linux/amd64
    build: .
    image: "rhub/api-rversions:0.0.18"
    environment:
      - REDIS_HOST=redis
      - PORT=3000
    depends_on:
      - redis
    ports:
      - "80:3000"

  redis:
     image: "redis:4.0.11-alpine"
     volumes:
     - rversions-data:/data
