name: Main CI
on:
  push:
    branches: [main, master, v2]
  pull_request:
    branches: [main, master, v2]
  workflow_dispatch:

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          docker compose build
          docker compose up -d
          npm install
          sleep 10
          docker compose ps || true
          docker compose logs rversions || true
          curl -v http://localhost:3000/rversions/resolve/next/win
          npm test
          docker compose down
